<?php
include_once('OAuth.php');

//pesapal params
$token = $params = NULL;

/*
PesaPal Sandbox is at https://demo.pesapal.com. Use this to test your developement and 
when you are ready to go live change to https://www.pesapal.com.
*/
$consumer_key = P_G_PK;//Register a merchant account on
                   //demo.pesapal.com and use the merchant key for testing.
                   //When you are ready to go live make sure you change the key to the live account
                   //registered on www.pesapal.com!
$consumer_secret = P_G_SK;// Use the secret from your test
                   //account on demo.pesapal.com. When you are ready to go live make sure you 
                   //change the secret to the live account registered on www.pesapal.com!
$signature_method = new OAuthSignatureMethod_HMAC_SHA1();
$iframelink = 'https://www.pesapal.com/api/PostPesapalDirectOrderV4';//change to      
                   //https://www.pesapal.com/API/PostPesapalDirectOrderV4 when you are ready to go live!

//get form details
$amount = $_POST['data']['amount'];
$amount = number_format($amount, 2);//format amount to 2 decimal places

$metadata_array = json_decode($_POST['data']['metadata'], true);

$desc = base64_encode($_POST['data']['metadata']);
$type = "MERCHANT"; //default value = MERCHANT
$reference = crypto_string(); //generate a random string as transaction ID;//unique order id of the transaction, generated by merchant
$first_name = $_POST['data']['user_firstname'];
$last_name = $_POST['data']['user_lastname'];
$email = $_POST['data']['email'];
$phonenumber = $_POST['data']['user_phone'];//ONE of email or phonenumber is required
$currency = $_POST['data']['currency'];
$callback_url = SITE_URL . 'paynotify.php?callback=true&resp=success'; //redirect url, the page that will handle the response from pesapal.

$post_xml = "<?xml version=\"1.0\" encoding=\"utf-8\"?><PesapalDirectOrderInfo xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\" Amount=\"".$amount."\" Description=\"".$desc."\" Type=\"".$type."\" Reference=\"".$reference."\" FirstName=\"".$first_name."\" LastName=\"".$last_name."\" Email=\"".$email."\" PhoneNumber=\"".$phonenumber."\" Currency=\"".$currency."\" xmlns=\"http://www.pesapal.com\"></PesapalDirectOrderInfo>
";

$post_xml = htmlentities($post_xml);

$consumer = new OAuthConsumer($consumer_key, $consumer_secret);

//post transaction to pesapal
$iframe_src = OAuthRequest::from_consumer_and_token($consumer, $token, "GET", $iframelink, $params);
$iframe_src->set_parameter("oauth_callback", $callback_url);
$iframe_src->set_parameter("pesapal_request_data", $post_xml);
$iframe_src->sign_request($signature_method, $consumer, $token);

//save data to database
//add transaction to gateways database table
$query = sprintf('INSERT INTO %stbl_pgateway (transaction_ref,amount,`date`,cur,user_id,user_type,gateway,memo) VALUES ("%s","%s","%s","%s","%d","%d","%s","%s")', 
DB_TBL_PREFIX,
$reference,
$_POST['data']['amount'],
gmdate('Y-m-d H:i:s', time()),
$_POST['data']['currency'],
$metadata_array['user_id'],
$metadata_array['user_type'],
"pesapal",
mysqli_real_escape_string($GLOBALS['DB'],$_POST['data']['metadata'])

);

if(!$result = mysqli_query($GLOBALS['DB'], $query)){
    $data = array('error'=>'Unable to Initialize transaction: DB write error');
    echo json_encode($data);
    exit; 
}




//display pesapal - iframe and pass iframe_src
ob_start();
echo $iframe_src;
$data = array('success'=>1,'pesapal_data'=>SITE_URL . "paynotify.php?redir-referrer=" . base64_encode(ob_get_clean()));
echo json_encode($data);
exit;
?>