	<?php

	$merchant_id 	= P_G_MERCHANT_ID;
	$merchant_key 	= P_G_PK;
	$merchant_salt	= P_G_SALT_K;

    $reference = crypto_string(); //generate a random string as transaction ID;//unique order id of the transaction, generated by merchant
    $metadata_array = $_POST['data']['metadata'];

	$email = $_POST['data']['email'];
	$payment_amount	= (int) $_POST['data']['amount'];
	$merchant_oid = $reference;
	$user_name = $_POST['data']['user_firstname'] . " " . $_POST['data']['user_lastname'];
	$user_address = "User default location";
	$user_phone = $_POST['data']['user_phone'];
	$merchant_ok_url = SITE_URL . "paynotify.php?callback=true&resp=success";
	$merchant_fail_url = SITE_URL . "paynotify.php?callback=true&resp=failed";
	$user_basket = base64_encode(json_encode(array(
		array($_POST['data']['metadata']['memo'], $payment_amount, 1)// 1st Product (Product Name - Unit Price - Piece)
	)));
	
	/* EXAMPLE $user_basket creation - You can duplicate arrays per each product
	$user_basket = base64_encode(json_encode(array(
		array("Sample Product 1", "18.00", 1), // 1st Product (Product Name - Unit Price - Piece)
		array("Sample Product 2", "33.25", 2), // 2nd Product (Product Name - Unit Price - Piece)
    	array("Sample Product 3", "45.42", 1)  // 3rd Product (Product Name - Unit Price - Piece)
	)));
	 */

	if( isset( $_SERVER["HTTP_CLIENT_IP"] ) ) {
		$ip = $_SERVER["HTTP_CLIENT_IP"];
	} elseif( isset( $_SERVER["HTTP_X_FORWARDED_FOR"] ) ) {
		$ip = $_SERVER["HTTP_X_FORWARDED_FOR"];
	} else {
		$ip = $_SERVER["REMOTE_ADDR"];
	}

	$user_ip=$ip;
	$timeout_limit = "30";
	$debug_on = 1;
    $test_mode = 0;
	$no_installment	= 0;
	$max_installment = 0;
	$currency = "TL";

	$hash_str = $merchant_id .$user_ip .$merchant_oid .$email .$payment_amount .$user_basket.$no_installment.$max_installment.$currency.$test_mode;
	$paytr_token=base64_encode(hash_hmac('sha256',$hash_str.$merchant_salt,$merchant_key,true));
	$post_vals=array(
			'merchant_id'=>$merchant_id,
			'user_ip'=>$user_ip,
			'merchant_oid'=>$merchant_oid,
			'email'=>$email,
			'payment_amount'=>$payment_amount,
			'paytr_token'=>$paytr_token,
			'user_basket'=>$user_basket,
			'debug_on'=>$debug_on,
			'no_installment'=>$no_installment,
			'max_installment'=>$max_installment,
			'user_name'=>$user_name,
			'user_address'=>$user_address,
			'user_phone'=>$user_phone,
			'merchant_ok_url'=>$merchant_ok_url,
			'merchant_fail_url'=>$merchant_fail_url,
			'timeout_limit'=>$timeout_limit,
			'currency'=>$currency,
            'test_mode'=>$test_mode
		);

	$ch=curl_init();
	curl_setopt($ch, CURLOPT_URL, "https://www.paytr.com/odeme/api/get-token");
	curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
	curl_setopt($ch, CURLOPT_POST, 1) ;
	curl_setopt($ch, CURLOPT_POSTFIELDS, $post_vals);
	curl_setopt($ch, CURLOPT_FRESH_CONNECT, true);
	curl_setopt($ch, CURLOPT_TIMEOUT, 20);
    curl_setopt($ch, CURLOPT_SSL_VERIFYPEER, 0);

    //XXX: DİKKAT: lokal makinanızda "SSL certificate problem: unable to get local issuer certificate" uyarısı alırsanız eğer
    //aşağıdaki kodu açıp deneyebilirsiniz. ANCAK, güvenlik nedeniyle sunucunuzda (gerçek ortamınızda) bu kodun kapalı kalması çok önemlidir!
    //curl_setopt($ch, CURLOPT_SSL_VERIFYPEER, 0);

    $result = @curl_exec($ch);

	if(curl_errno($ch)){
        $data = array('error'=>'Unable to Initialize transaction');
        echo json_encode($data);
        exit; 
		
    }
	curl_close($ch);

	$result=json_decode($result,1);

	if($result['status']=='success')
		$token=$result['token'];
	else{
        $data = array('error'=>'Unable to Initialize transaction');
        echo json_encode($data);
        exit; 
    }

    //save data to database
    //add transaction to gateways database table
    $query = sprintf('INSERT INTO %stbl_pgateway (transaction_ref,amount,`date`,cur,user_id,user_type,gateway,memo) VALUES ("%s","%s","%s","%s","%d","%d","%s","%s")', 
    DB_TBL_PREFIX,
    $reference,
    $payment_amount / 100,
    gmdate('Y-m-d H:i:s', time()),
    $metadata_array['cur_code'],
    $metadata_array['user_id'],
    $metadata_array['user_type'],
    "paytr",
    mysqli_real_escape_string($GLOBALS['DB'],json_encode($_POST['data']['metadata']))

    );

    if(!$result = mysqli_query($GLOBALS['DB'], $query)){
        $data = array('error'=>'Unable to Initialize transaction: DB write error');
        echo json_encode($data);
        exit; 
    }

    $data = array('success'=>1,'paytr_data'=>SITE_URL . "paynotify.php?redir-referrer=" . base64_encode($token));
    echo json_encode($data);
    exit;

	?>